const vi = {
  'common.loading': 'Đang tải',
  'common.connectionError': 'Lỗi kết nối mạng',
  'common.error': 'Rất tiếc đã có lỗi xảy ra. Vui lòng thực hiện lại thao tác.',
  'common.empty': 'Không có dữ liệu',
  'common.errorTitle': 'Lỗi',
  'common.close': 'Đóng',
  'common.cancel': 'Hủy',
  'common.save': 'Lưu',
  'common.dataSync': 'Đang đồng bộ dữ liệu',
  'common.errorDataSync': 'Lỗi đồng bộ dữ liệu',
  'common.warning': 'Cảnh báo',
  'common.notice': 'Thông báo',
  'common.iUnderstand': 'Tôi đã hiểu',
  'common.imSure': 'Tôi chắc chắn',
  'common.sorryError': 'Rất tiếc, đã có lỗi xảy ra',
  'common.year': 'năm',
  'common.month': 'tháng',
  'common.day': 'ngày',
  'common.hour': 'giờ',
  'common.minute': 'phút',
  'common.confirm': 'Xác nhận',
  'common.continue': 'Tiếp tục',
  'common.update': 'Cập nhật',
  'common.contactNow': 'Liên hệ ngay',
  'common.agree': 'Đồng ý',
  'common.systemError': 'Lỗi hệ thống',
  'common.retry': 'Thực hiện lại',
  'common.retrySelect': 'Lựa chọn lại',

  'login.welcome': 'Yeah! Được gặp nhau rồi ^_^',
  'login.phoneOrUserName': 'Số điện thoại/Tên đăng nhập',
  'login.phone': 'Số điện thoại',
  'login.password': 'Mật khẩu',
  'login.deviceId': 'Device ID: {{deviceId}}',
  'login.forgotPassword': 'Quên mật khẩu',
  'login.login': 'Đăng nhập',
  'login.orLoginWith': 'Hoặc đăng nhập với',
  'login.haventAccount': 'Ba mẹ chưa có tài khoản?',
  'login.register': 'Đăng ký',
  'login.quickLogin': 'Đăng nhập nhanh',

  'mergeAccount.validAccount.title': 'Kích hoạt thành công',
  'mergeAccount.validAccount.description':
    'Chúc mừng Ba mẹ đã kích hoạt thành công khoá học',
  'mergeAccount.validAccount.continue': 'Tiếp tục',
  'mergeAccount.informationAccountHasError':
    'Rất tiếc, thông tin gói học đã gặp lỗi. Vui lòng liên hệ Monkey Care số 1900636052 để được hỗ trợ.',
  'mergeAccount.accountHasLifeTime':
    'Tài khoản đã có gói học {{packageName}} trọn đời, vui lòng đăng nhập tài khoản khác hoặc đăng ký mới',
  'mergeAccount.activeSuccess': 'Kích hoạt thành công',
  'mergeAccount.mergeLifetimeToPaid':
    'Khóa học {{courseName}} vẫn còn hạn sử dụng, ba mẹ có chắc chắn muốn cộng thời hạn lên trọn đời?',
  'parents.tabs.report': 'Báo cáo',
  'parents.tabs.course': 'Khóa học',
  'parents.tabs.notification': 'Thông báo',
  'parents.tabs.setting': 'Cài đặt',
  'parents.courseSetting.header': 'Cài đặt khóa học',
  'parents.setting.header': 'Dành cho ba mẹ',
  'parents.setting.changeAvatar': 'Thay đổi hình đại diện',
  'parents.setting.account': 'THÔNG TIN PHỤ HUYNH',
  'parents.setting.deviceId': 'Device ID',
  'parents.setting.userId': 'User ID',
  'parents.setting.management': 'QUẢN LÝ NGƯỜI HỌC',
  'parents.setting.setting': 'CÀI ĐẶT',
  'parents.setting.support': 'HỖ TRỢ',
  'parents.setting.logout': 'Đăng xuất',
  'parents.setting.deleteAccount': 'Xóa tài khoản',
  'parents.parentInformation.header': 'Thông tin phụ huynh',
  'parents.parentInformation.fullName': 'Họ và tên:',
  'parents.parentInformation.fullNamePlaceholder': 'Họ và tên',
  'parents.parentInformation.phone': 'Số điện thoại:',
  'parents.parentInformation.phonePlaceholder': 'Số điện thoại',
  'parents.parentInformation.email': 'Email:',
  'parents.parentInformation.emailPlaceholder': 'Email',
  'parents.parentInformation.save': 'Lưu',
  'parents.popupUpdateParentInfo.title': 'Thành công',
  'parents.popupUpdateParentInfo.phoneNumber': 'Số điện thoại',
  'parents.popupUpdateParentInfo.description':
    'Từ bây giờ ba mẹ có thể đăng nhập với {{contact}} này.',
  'parents.popupUpdateParentInfo.understand': 'Tôi đã hiểu',
  'parents.childrenProfile.header': 'Hồ sơ học tập của con',
  'parents.childrenProfile.age': 'tuổi',
  'parents.childrenProfile.addProfile': 'Thêm người học',
  'parents.childProfile.changeAvatar': 'Thay đổi hình đại diện',
  'parents.childProfile.header': 'Hồ sơ của {{profile}}',
  'parents.childProfile.info': 'Thông tin',
  'parents.childProfile.course': 'Khóa học',
  'parents.childProfile.fullName': 'Họ và tên',
  'parents.childProfile.birthYear': 'Năm sinh',
  'parents.childProfile.target': 'Mục tiêu',
  'parents.childProfile.save': 'Lưu',
  'parents.childProfile.setStudyTime': 'Cài đặt thời gian học',
  'parents.childProfile.timeBetweenTwoStudies': 'Thời gian giữa 2 lần học',
  'parents.childProfile.birthYearPlaceholder': 'Năm sinh',
  'parents.childProfile.targetPlaceholder': 'Mục tiêu',
  'parents.setting.timeexpired': 'Hạn sử dụng khóa học',
  'parent.timeexpire.desc1': 'Còn lại',
  'parent.timeexpire.desc': 'Ngày hết hạn',
  'parent.timeexpire.act': 'Gia hạn sử dụng',
  'parents.courseExpiryDate.empty': 'Bạn chưa tham gia khóa học nào',
  'parents.courseExpiryDate.trial': 'Học thử',
  'parents.courseExpiryDate.lifetime': 'Trọn đời',
  'parents.setting.changepw': 'Thay đổi mật khẩu',
  'parents.changePassword.currentPassword': 'Mật khẩu hiện tại',
  'parents.changePassword.newPassword': 'Mật khẩu mới',
  'parents.changePassword.renewPassword': 'Nhập lại mật khẩu',
  'parents.changePassword.saveChange': 'Lưu thay đổi',
  'parents.changePassword.forgotPassword': 'Quên mật khẩu',

  'parents.settingStudySchedule.header': 'Đặt lịch học',
  'parents.settingStudySchedule.selectTime': 'Chọn giờ',
  'parents.settingStudySchedule.mon': 'T2',
  'parents.settingStudySchedule.tue': 'T3',
  'parents.settingStudySchedule.wed': 'T4',
  'parents.settingStudySchedule.thu': 'T5',
  'parents.settingStudySchedule.fri': 'T6',
  'parents.settingStudySchedule.sat': 'T7',
  'parents.settingStudySchedule.sun': 'CN',
  'parents.settingStudySchedule.classScheduleReminder': 'Lưu lịch học',

  'parents.aboutMonkey': 'Về Monkey',
  'parents.termsOfUse': 'Điều khoản sử dụng',
  'parents.privacyPolicy': 'Chính sách bảo mật',
  'parents.frequentlyAskedQuestions': 'Câu hỏi thường gặp',
  'parents.contactMonkey': 'Liên hệ Monkey',

  'parents.learningReport.header': 'Báo cáo học tập',
  'parents.learningReport.startedFrom': 'Đã tham gia',
  'parents.learningReport.switchProfile': 'Đổi hồ sơ',
  'parents.learningReport.thisWeek': 'Tuần này',
  'parents.learningReport.skills': 'Kỹ năng',
  'parents.learningReport.allTime': 'Tổng kết',
  'parents.learningReport.lesson': 'Bài học',
  'parents.learningReport.minute': 'Phút',
  'parents.learningReport.word': 'Từ',
  'parents.learningReport.sentence': 'Câu',
  'parents.learningReport.story': 'Truyện',
  'parents.learningReport.listening': 'Nghe',
  'parents.learningReport.speaking': 'Nói',
  'parents.learningReport.reading': 'Đọc',
  'parents.learningReport.writing': 'Viết',
  'parents.learningReport.courseProgress': 'Tiến độ học tập',
  'parents.learningReport.course': 'Khóa học',
  'parents.learningReport.stage': 'Chặng',
  'parents.changeAvatarProfile.title': 'Thay đổi ảnh đại diện',
  'parents.changeAvatarProfile.setAvatar': 'Đặt làm ảnh đại diện',

  'parents.childProfile.target.op1': 'Từ vựng',
  'parents.childProfile.target.op2': 'Giao tiếp',
  'parents.childProfile.target.op3': 'Học trên lớp',
  'parents.childProfile.target.op4': 'Chứng chỉ (TOEIC, IELTS,...)',

  'parents.childProfile.setStudyTime.op1': 'Không giới hạn (Mặc định)',
  'parents.childProfile.setStudyTime.op2': '15 phút',
  'parents.childProfile.setStudyTime.op3': '30 phút',
  'parents.childProfile.setStudyTime.op4': '1 giờ',
  'parents.childProfile.setStudyTime.op5': '2 giờ',

  'parents.childProfile.timeBetweenTwoStudies.op1': 'Không giới hạn (Mặc định)',
  'parents.childProfile.timeBetweenTwoStudies.op2': '1 giờ',
  'parents.childProfile.timeBetweenTwoStudies.op3': '6 giờ',
  'parents.childProfile.timeBetweenTwoStudies.op4': '8 giờ',
  'parents.childProfile.timeBetweenTwoStudies.op5': '12 giờ',
  'parents.childProfile.timeBetweenTwoStudies.op6': '24 giờ',

  'parents.settingGeneral.header': 'Cài đặt chung',
  'parents.settingGeneral.displayLanguage': 'Ngôn ngữ hiển thị',
  'parents.settingGeneral.soundtrack': 'Nhạc nền',
  'parents.settingGeneral.notification': 'Thông báo',
  'parents.settingGeneral.version': 'Phiên bản',
  'parents.settingGeneral.vietnamese': 'Tiếng Việt',
  'parents.settingGeneral.english': 'Tiếng Anh',
  'parents.settingGeneral.thailand': 'Tiếng Thái Lan',
  'parents.settingGeneral.malaysia': 'Tiếng Malaysia',

  'popupConfirmPassword.title': 'Xác thực mật khẩu',
  'popupConfirmPassword.description':
    'Ba mẹ nhập mật khẩu để xác thực tài khoản và chỉnh sửa thông tin nhé!',
  'popupConfirmPassword.placeholder': 'Mật khẩu',
  'popupConfirmPassword.button.forgotPassword': 'Quên mật khẩu',

  'popupCreatePassword.title': 'Cập nhật mật khẩu',
  'popupCreatePassword.description':
    'Ba mẹ thêm mật khẩu để chỉnh sửa thông tin và đăng nhập trong lần sau nhé!',
  'popupCreatePassword.placeholder1': 'Mật khẩu mới',
  'popupCreatePassword.placeholder2': 'Xác nhận mật khẩu',

  'popupNoticeGotoSignUp.title': 'Được làm quen thêm rồi...',
  'popupNoticeGotoSignUp.description':
    'Ba mẹ hãy đăng ký tài khoản để Monkey cập nhật thông tin nhé!',
  'popupNoticeGotoSignUp.forLater': 'Để sau nha',
  'popupNoticeGotoSignUp.signUpNow': 'Đăng ký ngay',

  'notificationChangeAge.title': 'CẢNH BÁO',
  'notificationChangeAge.description1':
    'Ba mẹ chỉ có thể thay đổi tuổi 01 lần, ba mẹ có chắc chắn muốn thay đổi không?',
  'notificationChangeAge.description2':
    'Ba mẹ đã hết lượt chỉnh sửa tuổi của hồ sơ học tập này.',
  'notificationChangeAge.cancel': 'Tôi đã hiểu',
  'notificationChangeAge.sure': 'Tôi chắc chắn',
  'notificationChangeAge.understood': 'Tôi đã hiểu',
  'notificationConfirmLogout.title': 'ĐĂNG XUẤT',
  'notificationConfirmLogout.description':
    'Bạn chắc chắn muốn đăng xuất tài khoản này?',
  'notificationConfirmLogout.cancel': 'Hủy',
  'notificationConfirmLogout.logout': 'Đăng xuất',

  'intro.register': 'Học thử',
  'intro.login': 'Đăng nhập',
  'registerName.whatName': 'Monkey có thể gọi bé là ...',
  'registerName.continue': 'Tiếp tục',
  'registerName.placeholder': 'Họ và tên',
  'registerYearOfBirth.title': 'Năm sinh của {{name}} là...',
  'registerYearOfBirth.continue': 'Tiếp tục',
  'registerYearOfBirth.bornBefore': 'Sinh trước năm ',
  'courseProposal.finding':
    'Monkey đang lựa chọn khóa học phù hợp nhất, {{name}} chờ chút nhé!',
  'courseProposal.hadFound': 'Yeah! Mình tìm thấy rồi ^_^',
  'courseProposal.overview': 'Tổng quan',
  'courseProposal.buyNow': 'Mua ngay',
  'courseProposal.studyNow': 'Học ngay',
  'courseProposal.trialNow': 'Học thử ngay',
  'selectLevel.currentAbility': 'Tiếng Anh của bạn {{name}} đang ở mức nào?',
  'selectLevel.level1': 'Con chưa biết gì về tiếng Anh.',
  'selectLevel.level2': 'Con đã nhận biết được một số từ vựng đơn giản.',
  'selectLevel.level3': 'Con có thể đọc hiểu được những câu ngắn và đơn giản.',
  'selectLevel.level4': 'Con có thể đọc hiểu đoạn văn ngắn.',
  'initializingCourse.title': 'Khởi tạo lộ trình học tập',
  'initializingCourse.favoriteTopics': 'Tùy chỉnh theo chủ đề yêu thích',
  'initializingCourse.age': 'Tùy chỉnh theo độ tuổi',
  'initializingCourse.level': 'Tùy chỉnh theo trình độ',
  'initializingCourse.studyProgram': 'Khởi tạo lộ trình học',

  'validate.accountFullName': 'Vui lòng nhập 1 - 50 ký tự',
  'validate.nameNotValid': 'Họ tên không hợp lệ',
  'validate.yearOfBirthRequired': 'Vui lòng chọn năm sinh của bé',
  'validate.phoneMin': 'Số điện thoại tối thiểu 10 số',
  'validate.phoneValid': 'Số điện thoại không đúng định dạng',
  'validate.phoneAvailable': 'Số điện thoại khả dụng',
  'validate.phoneUnavailable': 'Số điện thoại không khả dụng',
  'validate.phoneRequire': 'Vui lòng nhập số điện thoại',
  'validate.phoneNotValid': 'Số điện thoại không hợp lệ',
  'validate.phoneMinMaxLength': 'Số điện thoại cần nhập 6 - 15 chữ số',
  'validate.passwordValid': 'Mật khẩu sai định dạng',
  'validate.passwordIncorrect': 'Mật khẩu không khớp, vui lòng nhập lại',
  'validate.passwordAvailable': 'Mật khẩu khả dụng',
  'validate.passwordInvalid': 'Mật khẩu không chính xác',
  'validate.passwordMatch': 'Mật khẩu trùng khớp',
  'validate.passwordNotMatch': 'Mật khẩu không khớp, vui lòng nhập lại',
  'validate.maxPassword': 'Vui lòng nhập 1 - 30 ký tự',
  'validate.passwordRequire': 'Vui lòng nhập mật khẩu',
  'validate.currentPasswordRequire': 'Vui lòng nhập mật khẩu hiển tại',
  'validate.newPasswordRequire': 'Vui lòng nhập mật khẩu mới',
  'validate.renewPasswordRequire': 'Vui lòng nhập lại mật khẩu',
  'validate.email': 'Cần nhập đúng định dạng name@example.com',
  'validate.usernamePhoneRequired': 'Vui lòng nhập số điện thoại/tên đăng nhập',
  'validate.usernameDoesNotContainSpace': 'Tên đăng nhập không chứa dấu cách',
  'validate.nameAlreadyExists': 'Tên hồ sơ đã tồn tại',

  'notiAccNotExist.title': 'Thông báo',
  'notiAccNotExist.cancel': 'Hủy',
  'notiAccNotExist.resgister': 'Đăng ký',
  'notiAccAlreadyExist.title': 'Thông báo',
  'notiAccAlreadyExist.cancel': 'Tôi đã hiểu',
  'notiAccAlreadyExist.login': 'Đăng nhập',

  'notiLoginFail.title': 'Thông báo',
  'notiLoginFail.desc': '{{title}} bằng {{method}} thất bại. Vui lòng thử lại',
  'notiLoginFail.ok': 'Tôi đã hiểu',
  'notiLoginFail.login': 'Đăng nhập',
  'notiLoginFail.signup': 'Đăng ký',
  'notiLoginFail.facebook': 'Facebook',
  'notiLoginFail.google': 'Google',
  'notiLoginFail.apple': 'Apple',

  'forgotPassword.title': 'Quên mật khẩu',
  'forgotPassword.desc':
    'Ba mẹ đừng lo lắng, hãy nhập {{method}} để Monkey hỗ trợ cập nhật mật khẩu nhé.',
  'forgotPassword.sendOtp': 'Gửi OTP',
  'forgotPassword.phone': 'Số điện thoại',
  'forgotPassword.confirmOtp': 'Xác nhận OTP',
  'forgotPassword.monkeySent':
    'Monkey đã gửi mã OTP đến {{method}} \n{{value}}',
  'forgotPassword.phoneText': 'số điện thoại',
  'forgotPassword.emailText': 'email',
  'forgotPassword.confirm': 'Xác nhận',
  'forgotPassword.reSend': 'Gửi lại OTP {{second}}',
  'forgotPassword.wrongOtp': 'OTP không đúng, vui lòng nhập lại',
  'forgotPassword.whatMethodChoose':
    'Ba mẹ muốn nhận mã để đặt lại mật khẩu theo hình thức nào?',
  'forgotPassword.sentSMS': 'Gửi mã qua SMS',
  'forgotPassword.sentEmail': 'Gửi mã qua Email',
  'forgotPassword.or': 'Hoặc',
  'forgotPassword.email': 'Email',

  'updatePassword.title': 'Cập nhật mật khẩu',
  'updatePassword.newPass': 'Mật khẩu mới',
  'updatePassword.reNewPass': 'Xác nhận mật khẩu',
  'updatePassword.update': 'Cập nhật mật khẩu',
  'updatePassword.success': 'Yeah!! Cập nhật mật khẩu\nthành công ',
  'updatePassword.studyNow': 'Vào học ngay',
  'updatePassword.fail': 'Cập nhật mật khẩu thất bại',

  'notiMoreThan.title': 'Cảnh báo',
  'notiMoreThan.descMoreThan5Times':
    'Ba mẹ đã nhập sai mã OTP quá 5 lần.\nVui lòng quay trở lại sau 5 phút.',
  'notiMoreThan.descMoreThan3TimesHour':
    'Ba mẹ đã thực hiện gửi lại quá 3 lần.\nVui lòng quay lại sau 60 phút.',
  'notiMoreThan.iUnderstand': 'Tôi đã hiểu',
  'notiInputPswIncorrect.title': 'Oops',
  'notiInputPswIncorrect.description':
    'Bạn đã nhập sai mật khẩu quá 5 lần.\nChọn quên mật khẩu để khôi phục.',
  'notiInputPswIncorrect.retry': 'Thử lại',
  'notiInputPswIncorrect.forgotPass': 'Quên mật khẩu',

  'signUp.welcome': 'Monkey xin chào ba mẹ!',
  'signUp.orSignUpWith': 'Hoặc đăng ký với',
  'signUp.iHaventAcc': 'Tôi đã có tài khoản',
  'signUp.login': 'Đăng nhập',
  'signUp.phone': 'Số điện thoại',
  'signUp.password': 'Mật khẩu',
  'signUp.rePassword': 'Nhập lại mật khẩu',
  'signUp.signUp': 'Đăng ký',
  'signUp.continue': 'Tiếp tục',
  'signUp.error': 'Rất tiếc, đã có lỗi xảy ra. Ba mẹ vui lòng thử lại.',
  'signUp.pleaseSetAnotherPass': 'Ba mẹ vui lòng đặt mật khẩu khác',
  'signUp.setPassword': 'Đặt mật khẩu',
  'signUpSuccess.title': 'Chào mừng ba mẹ và bé đến với Monkey Junior',
  'signUpSuccess.continue': 'Tiếp tục',

  'listProfileAfterSelectCourseStudy.who':
    'Ba mẹ muốn bạn nào\n học thử khóa học',
  'appHome.who': 'Monkey xin chào ^_^!\nHôm nay mình sẽ học cùng bạn...',
  'appHome.addProfile': 'Thêm người học',
  'appHome.parentSetting': 'Dành cho ba mẹ',

  'popupVerify.toContinue': 'Để tiếp tục, ba mẹ hãy nhập:',
  'popupVerify.one': 'một',
  'popupVerify.two': 'hai',
  'popupVerify.three': 'ba',
  'popupVerify.four': 'bốn',
  'popupVerify.five': 'năm',
  'popupVerify.six': 'sáu',
  'popupVerify.seven': 'bảy',
  'popupVerify.eight': 'tám',
  'popupVerify.nine': 'chín',

  'payment.title': 'Khóa học',
  'payment.save': 'SAVE {{percent}}%',
  'payment.desc': 'Hủy bất kỳ lúc nào',
  'payment.act': 'Mua ngay',
  'payment.policy': 'Điều khoản & chính sách',
  'payment.reactive': 'Khôi phục gói mua',
  'payment.success.title': 'Thanh toán thành công',
  'payment.changePackageSuccess': 'Đổi gói mua thành công', //
  'payment.changePackageDesc':
    'Ba mẹ sẽ tự động được gia hạn gói mua: {{packageName}} với giá {{price}} vào kì thanh toán tiếp theo: {{timeRenew}}.', //
  'payment.success.desc':
    'Monkey biết ba mẹ có nhiều lựa chọn, cảm ơn ba mẹ đã chọn Monkey để đồng hành cùng con.',
  'payment.success.act': 'Vào học ngay',
  'payment.restore.restoreSuccess': 'Khôi phục thành công', //
  'payment.restore.pleaseAddAccount':
    'Mời ba mẹ tạo tài khoản và hồ sơ học tập cho bé',
  'payment.restore.restoreFail': 'Khôi phục thất bại', //
  'payment.restore.pleaseCheckPackage': 'Ba mẹ vui lòng kiểm tra lại gói mua',
  'payment.restore.noPurchaseRestore':
    'Tài khoản Google/ Apple của ba mẹ chưa có gói mua khóa học {{courseName}}. Vui lòng kiểm tra lại!',
  'payment.restore.errorSystemMessage':
    'Lỗi mất kết nối. Ba mẹ vui lòng quay lại sau ít phút hoặc liên hệ với chăm sóc khách hàng qua số điện thoại 1900 63 60 52 để được hỗ trợ tốt nhất.',
  'payment.connectStore.serviceError':
    'Đã xảy ra lỗi khi xác nhận tài khoản. Vui lòng kiểm tra lại!',
  'payment.termsAndPolicies.title': 'Điều khoản & Chính sách',
  'payment.termsAndPolicies.contentIos':
    'Vui lòng xem Điều khoản sử dụng và Chính sách bảo mật để biết thêm thông tin. Đăng kí sẽ tự động gia hạn trừ khi tắt tính năng tự động gia hạn ít nhất 24 giờ trước thời hạn sử dụng. Tài khoản sẽ bị tính phí gia hạn với mức phí của gói học đã chọn trong vòng 24 giờ trước khi kết thúc thời hạn sử dụng. Bạn có thể vào phần Cài đặt trong tài khoản iTunes để quản lý đăng kí của mình và tắt tính năng tự động gia hạn. Tài khoản iTunes của bạn sẽ bị tính phí khi giao dịch mua được xác nhận. Ngay khi giao dịch mua được xác nhận, phần còn lại của bản dùng thử miễn phí sẽ không còn.',
  'payment.termsAndPolicies.contentAndroid':
    'Vui lòng xem Điều khoản sử dụng và Chính sách bảo mật để biết thêm thông tin. Đăng kí sẽ tự động gia hạn trừ khi tắt tính năng tự động gia hạn ít nhất 24 giờ trước thời hạn sử dụng. Tài khoản sẽ bị tính phí gia hạn với mức phí của gói học đã chọn trong vòng 24 giờ trước khi kết thúc thời hạn sử dụng. Bạn có thể vào phần Cài đặt trong tài khoản Google Play để quản lý đăng kí của mình và tắt tính năng tự động gia hạn. Tài khoản Google Play của bạn sẽ bị tính phí khi giao dịch mua được xác nhận. Ngay khi giao dịch mua được xác nhận, phần còn lại của bản dùng thử miễn phí sẽ không còn',

  'payment.popupc3.title': 'Ba mẹ đang cần hỗ trợ?',
  'payment.popupc3.desc': 'Hãy nói với Monkey nhé!',
  'payment.popupc3.name': 'Họ và tên',
  'payment.popupc3.phone': 'Số điện thoại',
  'payment.popupc3.act': 'Hỗ trợ tôi',
  'popupC3.requireName': 'Vui lòng nhập họ tên', //
  'popupC3.requireContact': 'Vui lòng nhập số điện thoại', //
  'payment.popupc3.success.title': 'Cập nhật thành công',
  'payment.popupc3.success.desc':
    'Monkey sẽ liên hệ hỗ trợ thông tin cho ba mẹ trong vòng 24h',
  'payment.popupc3.success.act': 'Tìm hiểu ưu đãi',
  'payment.popupc3.fail.title': 'Cập nhật thất bại',
  'payment.popupc3.fail.desc':
    'Rất tiếc, đã có lỗi xảy ra. Ba mẹ vui lòng thử lại.',
  'payment.popupc3.fail.act': 'Thử lại',

  'linkAccount.title': 'Ba mẹ sẽ sử dụng tài khoản này để học tập?',
  'linkAccount.accountInfo': 'Thông tin tài khoản',
  'linkAccount.name': 'Họ và tên',
  'linkAccount.email': 'Email',
  'linkAccount.phone': 'SĐT',
  'linkAccount.academicRecords': 'Hồ sơ học tập của con',
  'linkAccount.linkWithThisAccount': 'Đồng ý',
  'linkAccount.loginWithOtherAccount': 'Tôi đã có tài khoản',
  'linkAccountChooseSignInOrSignUp.description':
    'Để sử dụng gói mua, ba mẹ vui lòng',
  'linkAccountChooseSignInOrSignUp.or': ' hoặc ',
  'linkAccountChooseSignInOrSignUp.login': 'Đăng nhập',
  'linkAccountChooseSignInOrSignUp.createNewAccount': 'Tạo tài khoản mới',

  'errorNetwork.title': 'Lỗi không thể kết nối được với máy chủ',
  'errorNetwork.desc':
    'Vui lòng kiểm tra lại đường truyền mạng của bạn. Xin cảm ơn!',
  'errorNetwork.tryAgain': 'Thử lại',

  'popupAccoutHasActivated.desc':
    'Gói mua đã được liên kết với tài khoản: {{displayName}}, ba mẹ vui lòng đăng nhập để tiếp tục sử dụng.',
  'popupAccoutHasActivated.agree': 'Xác nhận',
  'popupAccoutHasActivated.login': 'Đăng nhập',

  'popupPackageNotExist.title': 'Thông báo',
  'popupPackageNotExist.desc':
    'Gói mua không tồn tại, ba mẹ vui lòng kiểm tra lại.',
  'popupPackageNotExist.submit': 'Xác nhận',

  'popupShowWarningLostProfile.title': 'Thông báo',
  'popupShowWarningLostProfile.description':
    'Ba mẹ sẽ mất đi hồ sơ học {{profileTrial}}, ba mẹ có muốn đăng nhập không?',
  'popupShowWarningLostProfile.login': 'Đăng nhập',

  'permission.requestAccess': 'Yêu cầu quyền truy cập',
  'permission.requestLibraryAccess':
    'Bạn cần cấp quyền truy cập Thư viện để sử dụng tính năng này',
  'permission.openSettings': 'Mở cài đặt',
  'permission.cantOpenLibrary': 'Không thể mở Thư viện ảnh',

  'parent.settingcource.title': 'Cài đặt khóa học',
  'setting.EE.title': 'Cài đặt khóa học',
  'setting.EE.guide': 'Huớng dẫn chọn đáp án',
  'setting.EE.b2c': 'Thời gian chuyển giữa 2 thẻ học',
  'setting.EE.b2c.title': 'Thời gian chuyển giữa 2 thẻ',
  'setting.LRC.changelevel': 'Thay đổi cấp độ',
  'parents.coursesSetting.chooseLevel': 'Chọn cấp độ',
  'setting.LRC.changelevel.title': 'Hệ thống cấp độ học',
  'setting.LRC.changelevel.word': 'Từ: {{numberOfWord}}',
  'setting.LRC.changelevel.lex': 'Lexile: {{lexile}}',
  'parents.coursesSetting.level.levelChangeWarning':
    'Ba mẹ chỉ có thể thay đổi cấp độ học 1 lần, ba mẹ có chắc chắn muốn thay đổi không?',
  'parents.coursesSetting.level.noticeNotToChangeLevel':
    'Ba mẹ đã hết lượt thay đổi cấp độ của hồ sơ học tập này',

  'parents.notification.header': 'Thông báo',
  'parents.notification.activities': 'Hoạt động',
  'parents.notification.news': 'Tin tức',

  'popup.notice.create.profile.title': 'Ba mẹ hãy tạo hồ sơ học cho bé nhé',
  'popup.notice.create.profile.desc':
    'Monkey sẽ đề xuất nội dung để xây dựng lộ trình học phù hợp cho bé',
  'popup.notice.create.profile.button': 'Tạo hồ sơ học ngay',

  'courseProposal.EE.title': 'Early Education',
  'courseProposal.EE.desc1':
    'Là khóa học dạy ngôn ngữ cho các bé với định hướng từ vựng, áp dụng các biện pháp Giáo dục sớm, kích thích đồng đều cả 2 bán cầu não.',
  'courseProposal.EE.desc21': 'Dành cho trẻ từ 0-6 tuổi',
  'courseProposal.EE.desc22':
    '800+ từ vựng, 2500+ câu và 140+ chủ điểm ngữ pháp',
  'courseProposal.EE.desc23': '50+ trò chơi tương tác thứ vị',

  'courseProposal.LRC.title': 'Leveled reading',
  'courseProposal.LRC.desc1':
    'Là khóa học giúp bé luyện tập, nâng cao khả năng tiếng Anh bằng phương pháp Đọc - Hiểu theo từng cấp độ tương đương với trình độ từ pre A1 đến A2',
  'courseProposal.LRC.desc21': 'Dành cho trẻ từ 2-10 tuổi',
  'courseProposal.LRC.desc22': '1000+ truyện tranh tương tác theo 14 cấp độ',
  'courseProposal.LRC.desc23': 'Tích hợp Công nghệ AI nhận diện giọng nói',

  'intro.scr1.title': 'Phương pháp học đa giác quan, đa tương tác',
  'intro.scr1.desc':
    'Áp dụng phương pháp giáo dục sớm tiên tiến\nTrẻ phát triển cân bằng IQ và EQ',
  'intro.scr2.title': 'Lộ trình phát triển ngôn ngữ toàn diện',
  'intro.scr2.desc':
    'Công nghệ AI giúp trẻ phát âm chuẩn Anh - Mỹ\nNhiều cấp độ phù hợp với mọi trẻ em',
  'intro.scr3.title': 'Siêu ứng dụng tiếng Anh trẻ em Top 5 thế giới',
  'intro.scr3.desc':
    '+1 triệu gia đình Mỹ tin tưởng sử dụng\n+15 triệu người dùng trên toàn thế giới',

  'package.6months': '6 tháng',
  'package.lifetime': 'trọn đời',
  'package.1years': '1 năm',
  'payment.package': 'Gói {{packageName}}',
  'requestCreateAccount.pleaseGoToCreateAccount':
    'Gói mua đã được kích hoạt. Ba mẹ vui lòng tạo tài khoản để sử dụng.',
  'requestCreateAccount.createAccount': 'Tạo tài khoản',
};
